/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.cinema.view;

import com.mycompany.cinema.dao.FilmeDao;
import com.mycompany.cinema.dao.HorarioDao;
import com.mycompany.cinema.dao.PoltronaDao;
import com.mycompany.cinema.entidade.Filme;
import com.mycompany.cinema.entidade.HorarioSessao;
import com.mycompany.cinema.entidade.Poltrona;
import com.mycompany.cinema.model.HorarioSessaoListModel;
import com.mycompany.cinema.model.PoltronaListModel;
import com.mycompany.cinema.util.Util;

import javax.swing.*;
import javax.swing.table.TableModel;
import java.util.List;

public class IfrHorarioSessaoListagem extends JInternalFrame {
    private final HorarioDao horarioDao = new HorarioDao();
    private final FilmeDao filmeDao = new FilmeDao();
    private HorarioSessaoListModel horarioSessaoListModel = null;

    public IfrHorarioSessaoListagem() {
        initComponents();
        super.setTitle("Listagem de horários");
        buscaFilmes();
    }

    private void buscaFilmes() {
        List<Filme> filmes = filmeDao.findAll();
        if(!Util.listNuloOuVazio(filmes)){
            filmes.forEach(f -> jFilme.addItem(f));
        }
    }

    public void atualizaListaDeHorarios() {
        Filme filmeSelecionado = (Filme) jFilme.getSelectedItem();
        if (filmeSelecionado != null) {
            List<HorarioSessao> horarios = horarioDao.buscaHorariosPeloFilmeEDataMaiorQueAtual(filmeSelecionado);
            horarioSessaoListModel = new HorarioSessaoListModel(horarios);
            limpaForm();
            jTable1.setModel(horarioSessaoListModel);
        }
    }

    private void limpaForm() {
        jFilme.setSelectedItem(new Filme());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jFilme = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        buscarHorariosBt = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jselecionar = new javax.swing.JButton();
        jFechar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel2.setText("Selecione o filme que deseja assistir");

        jFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFilmeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFilme, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(333, 333, 333))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setText("Lista de horários");

        buscarHorariosBt.setText("Buscar");
        buscarHorariosBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarHorariosBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarHorariosBt)
                        .addGap(40, 40, 40))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(buscarHorariosBt))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addContainerGap())
        );

        jselecionar.setText("Selecionar");
        jselecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jselecionarActionPerformed(evt);
            }
        });
        jPanel4.add(jselecionar);

        jFechar.setText("Fechar");
        jFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFecharActionPerformed(evt);
            }
        });
        jPanel4.add(jFechar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jselecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jselecionarActionPerformed
        int linhaSelecionada = jTable1.getSelectedRow();
        if (linhaSelecionada >= 0) {
            if (horarioSessaoListModel != null){
                HorarioSessao horarioSessao = horarioSessaoListModel.getHorarioSessaoPorLinha(linhaSelecionada);
               JFrame.horarioSessaoListagem(horarioSessao);
            }
        }
        save();
    }//GEN-LAST:event_jselecionarActionPerformed

    private void codigoPoltronaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoPoltronaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoPoltronaTextActionPerformed

    private void jFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFilmeActionPerformed
    }//GEN-LAST:event_jFilmeActionPerformed

    private void buscarHorariosBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarHorariosBtActionPerformed
        atualizaListaDeHorarios();
    }//GEN-LAST:event_buscarHorariosBtActionPerformed

    private void jFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFecharActionPerformed
        limpaForm();
        this.dispose();
    }//GEN-LAST:event_jFecharActionPerformed

    private void fecharActionPerformed(java.awt.event.ActionEvent evt) {                                       
        limpaForm();
        this.dispose();
    }

    private void limparFormActionPerformed(java.awt.event.ActionEvent evt) {                                           
        limpaForm();
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int linhaSelecionada = jTable1.getSelectedRow();
        if (linhaSelecionada >= 0) {
//            Long idPoltrona = (Long) jTable1.getValueAt(linhaSelecionada, 0);
//            Poltrona salaDoBanco = horarioDao.findById(idPoltrona);
//            if(salaDoBanco != null){
//                poltronaId.setText(salaDoBanco.getId().toString());
//                codigoPoltronaText.setText(salaDoBanco.getCodigo());
//            }
        }
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int linhaSelecionada = jTable1.getSelectedRow();
        if (linhaSelecionada >= 0) {
            int opcao = JOptionPane.showConfirmDialog(null, "Deseja excluir a poltrona selecionada?",
                    "Exclusão",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (opcao == JOptionPane.YES_OPTION) {
                Long idPoltrona = (Long) jTable1.getValueAt(linhaSelecionada, 0);
                if(horarioDao.delete(idPoltrona)){
                    JOptionPane.showMessageDialog(null, "Poltrona excluída com sucesso!");
                }

                atualizaListaDeHorarios();
                }
            }
        else {
            JOptionPane.showMessageDialog(null, "SELECIONE UM REGISTRO!");
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarHorariosBt;
    private javax.swing.JButton jFechar;
    private javax.swing.JComboBox<Filme> jFilme;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jselecionar;
    // End of variables declaration//GEN-END:variables

    private HorarioSessao getPoltrona() {
//        Poltrona poltrona = null;
//        if(!codigoPoltronaText.getText().equals("")){
//            poltrona = new Poltrona();
//            if(!poltronaId.getText().equals("")){
//                poltrona.setId(Long.valueOf(poltronaId.getText()));
//            }
//            poltrona.setCodigo(codigoPoltronaText.getText());
//        }
//        return poltrona;
        return new HorarioSessao();
    }

    private void save() {
        Poltrona sala = null;
        if (sala != null) {
            if(sala.getId() != null){
//                horarioDao.update(sala);
            } else{
//                horarioDao.insert(sala);
            }
        }
            atualizaListaDeHorarios();
    }
}
