/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.cinema.view;

import com.mycompany.cinema.dao.PedidoDao;
import com.mycompany.cinema.dao.PedidoPoltronaDao;
import com.mycompany.cinema.dao.PoltronaDao;
import com.mycompany.cinema.entidade.*;
import com.mycompany.cinema.model.HorarioSessaoListModel;
import com.mycompany.cinema.util.Util;

import javax.swing.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class IfrPoltronasListagem extends JInternalFrame {
    private final PoltronaDao poltronaDao = new PoltronaDao();
    private final PedidoDao pedidoDao = new PedidoDao();
    private final PedidoPoltronaDao pedidoPoltronaDao = new PedidoPoltronaDao();
    private HorarioSessaoListModel horarioSessaoListModel = null;
    private HorarioSessao horarioSessao;

    public IfrPoltronasListagem(HorarioSessao horarioSessao) {
        initComponents();
        super.setTitle("Listagem de poltronas");
        if(horarioSessao != null){
            this.horarioSessao = horarioSessao;
            verificaPoltronasCompradas(horarioSessao);
        }
    }

    private void verificaPoltronasCompradas(HorarioSessao horarioSessao) {
        List<Poltrona> poltronas = poltronaDao.buscaPoltronasIndisponiveis(horarioSessao.getFilme().getId(), horarioSessao.getSala().getId());
        List<JRadioButton> radionButtons = getRadionButtons();
        if(!Util.listNuloOuVazio(poltronas) && !Util.listNuloOuVazio(radionButtons)){
            poltronas.forEach(poltrona -> {
                radionButtons.forEach(jRadioButton -> {
                    if(poltrona.getCodigo().equals(jRadioButton.getText())){
                        jRadioButton.setEnabled(false);
                        jRadioButton.setSelected(true);
                    }
                });
            });
        }
    }

    private List<JRadioButton> getRadionButtons() {
        return new ArrayList<>(Arrays.asList(A1, A2, A3, A4, A5, A6,
                                             B1, B2, B3, B4, B5, B6,
                                             C1, C2, C3, C4, C5, C6,
                                             D1, D2, D3, D4, D5, D6));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        A1 = new javax.swing.JRadioButton();
        A2 = new javax.swing.JRadioButton();
        A3 = new javax.swing.JRadioButton();
        A4 = new javax.swing.JRadioButton();
        A5 = new javax.swing.JRadioButton();
        A6 = new javax.swing.JRadioButton();
        B1 = new javax.swing.JRadioButton();
        B2 = new javax.swing.JRadioButton();
        B3 = new javax.swing.JRadioButton();
        B4 = new javax.swing.JRadioButton();
        B5 = new javax.swing.JRadioButton();
        B6 = new javax.swing.JRadioButton();
        C1 = new javax.swing.JRadioButton();
        C2 = new javax.swing.JRadioButton();
        C3 = new javax.swing.JRadioButton();
        C4 = new javax.swing.JRadioButton();
        C5 = new javax.swing.JRadioButton();
        C6 = new javax.swing.JRadioButton();
        D1 = new javax.swing.JRadioButton();
        D2 = new javax.swing.JRadioButton();
        D3 = new javax.swing.JRadioButton();
        D4 = new javax.swing.JRadioButton();
        D5 = new javax.swing.JRadioButton();
        D6 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jCompra = new javax.swing.JButton();
        jFechar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel2.setText("Selecione as poltronas que deseja");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        A1.setText("A-1");

        A2.setText("A-2");

        A3.setText("A-3");

        A4.setText("A-4");

        A5.setText("A-5");

        A6.setText("A-6");

        B1.setText("B-1");

        B2.setText("B-2");

        B3.setText("B-3");

        B4.setText("B-4");

        B5.setText("B-5");

        B6.setText("B-6");

        C1.setText("C-1");

        C2.setText("C-2");

        C3.setText("C-3");

        C4.setText("C-4");

        C5.setText("C-5");

        C6.setText("C-6");

        D1.setText("D-1");

        D2.setText("D-2");

        D3.setText("D-3");

        D4.setText("D-4");
        D4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D4ActionPerformed(evt);
            }
        });

        D5.setText("D-5");

        D6.setText("D-6");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A1)
                    .addComponent(B1)
                    .addComponent(C1)
                    .addComponent(D1))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B2)
                    .addComponent(A2)
                    .addComponent(C2)
                    .addComponent(D2))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A3)
                    .addComponent(B3)
                    .addComponent(C3)
                    .addComponent(D3))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A4)
                    .addComponent(B4)
                    .addComponent(C4)
                    .addComponent(D4))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A5)
                    .addComponent(B5)
                    .addComponent(C5)
                    .addComponent(D5))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(D6)
                    .addComponent(C6)
                    .addComponent(A6)
                    .addComponent(B6))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A1)
                    .addComponent(A2)
                    .addComponent(A3)
                    .addComponent(A4)
                    .addComponent(A5)
                    .addComponent(A6))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B1)
                    .addComponent(B2)
                    .addComponent(B3)
                    .addComponent(B4)
                    .addComponent(B5)
                    .addComponent(B6))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C1)
                    .addComponent(C2)
                    .addComponent(C3)
                    .addComponent(C4)
                    .addComponent(C5)
                    .addComponent(C6))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D1)
                    .addComponent(D2)
                    .addComponent(D3)
                    .addComponent(D4)
                    .addComponent(D5)
                    .addComponent(D6))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jCompra.setText("Comprar");
        jCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCompraActionPerformed(evt);
            }
        });
        jPanel4.add(jCompra);

        jFechar.setText("Fechar");
        jFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFecharActionPerformed(evt);
            }
        });
        jPanel4.add(jFechar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCompraActionPerformed
        List<JRadioButton> radionButtons = getRadionButtons();
        if(!Util.listNuloOuVazio(radionButtons)) {

            List<JRadioButton> radiosButtonsSeleconados = radionButtons.stream().filter(radionButton -> radionButton.isSelected() && radionButton.isEnabled()).toList();
            List<Poltrona> poltronas = poltronaDao.findAll();
            List<Poltrona> poltronasSelecionadas = null;
            if (!Util.listNuloOuVazio(radiosButtonsSeleconados) && !Util.listNuloOuVazio(poltronas)) {
                poltronasSelecionadas = poltronas.stream().filter(poltrona ->
                        radiosButtonsSeleconados.stream().anyMatch(radionButton -> radionButton.getText().equals(poltrona.getCodigo()))).toList();

            }
            if (!Util.listNuloOuVazio(poltronasSelecionadas)) {
                Pedido pedido = criaPedido();
                poltronasSelecionadas.forEach(poltrona -> {
                    pedidoPoltronaDao.insert(new PedidoPoltrona(new Poltrona(poltrona.getId()), pedido));
                });
                mensagemConfirmacaoCompra();
            }
        }
    }//GEN-LAST:event_jCompraActionPerformed

    private void mensagemConfirmacaoCompra(){
        JOptionPane.showMessageDialog(null, "Compra feita!");
        this.dispose();
    }

    public Pedido criaPedido(){
        Pedido pedido = new Pedido(new Sala(horarioSessao.getSala().getId()),
                new Filme(horarioSessao.getFilme().getId()),
                LocalDateTime.now());
        return pedidoDao.insert(pedido);
    }

    private void codigoPoltronaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoPoltronaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoPoltronaTextActionPerformed

    private void jFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_jFecharActionPerformed

    private void D4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D4ActionPerformed

    private void fecharActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    private void limparFormActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A1;
    private javax.swing.JRadioButton A2;
    private javax.swing.JRadioButton A3;
    private javax.swing.JRadioButton A4;
    private javax.swing.JRadioButton A5;
    private javax.swing.JRadioButton A6;
    private javax.swing.JRadioButton B1;
    private javax.swing.JRadioButton B2;
    private javax.swing.JRadioButton B3;
    private javax.swing.JRadioButton B4;
    private javax.swing.JRadioButton B5;
    private javax.swing.JRadioButton B6;
    private javax.swing.JRadioButton C1;
    private javax.swing.JRadioButton C2;
    private javax.swing.JRadioButton C3;
    private javax.swing.JRadioButton C4;
    private javax.swing.JRadioButton C5;
    private javax.swing.JRadioButton C6;
    private javax.swing.JRadioButton D1;
    private javax.swing.JRadioButton D2;
    private javax.swing.JRadioButton D3;
    private javax.swing.JRadioButton D4;
    private javax.swing.JRadioButton D5;
    private javax.swing.JRadioButton D6;
    private javax.swing.JButton jCompra;
    private javax.swing.JButton jFechar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

}
