/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cinema.view;

import com.mycompany.cinema.conexao.Conexao;
import com.mycompany.cinema.dao.PedidoDao;
import com.mycompany.cinema.dao.PoltronaDao;
import com.mycompany.cinema.entidade.Poltrona;
import com.mycompany.cinema.util.Util;

import javax.swing.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author Arthur
 */
public class JFrame extends javax.swing.JFrame {
    private final PoltronaDao poltronaDao = new PoltronaDao();
    private final PedidoDao pedidoDao = new PedidoDao();


    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
        super.setExtendedState(MAXIMIZED_BOTH);
        verificaPoltronasCompradas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        A1 = new javax.swing.JRadioButton();
        A2 = new javax.swing.JRadioButton();
        A3 = new javax.swing.JRadioButton();
        comprar = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuFilme = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuSala = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jHorariosMenu = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jPoltronaMenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        A1.setText("A-1");
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });

        A2.setText("A-2");

        A3.setText("A-3");
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });

        comprar.setText("COMPRAR");
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastro");

        jMenuFilme.setText("Filmes");
        jMenuFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFilmeActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuFilme);
        jMenu1.add(jSeparator1);

        jMenuSala.setText("Salas");
        jMenuSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSala);
        jMenu1.add(jSeparator3);

        jHorariosMenu.setText("Horários");
        jHorariosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHorariosMenuActionPerformed(evt);
            }
        });
        jMenu1.add(jHorariosMenu);
        jMenu1.add(jSeparator4);

        jPoltronaMenu.setText("Poltronas");
        jPoltronaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPoltronaMenuActionPerformed(evt);
            }
        });
        jMenu1.add(jPoltronaMenu);
        jMenu1.add(jSeparator2);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(427, Short.MAX_VALUE)
                .addComponent(comprar)
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(A1)
                .addGap(18, 18, 18)
                .addComponent(A2)
                .addGap(18, 18, 18)
                .addComponent(A3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A1)
                    .addComponent(A2)
                    .addComponent(A3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDesktopPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comprar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A1ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jHorariosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHorariosMenuActionPerformed
        IfrHorarioSessao irfHorarioSessao = new IfrHorarioSessao();
        jDesktopPane1.add(irfHorarioSessao);
        Util.centralizarFrame(irfHorarioSessao);
        irfHorarioSessao.setVisible(true);
    }//GEN-LAST:event_jHorariosMenuActionPerformed

    private void jPoltronaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPoltronaMenuActionPerformed
        IfrPoltronas ifrPoltronas = new IfrPoltronas();
        jDesktopPane1.add(ifrPoltronas);
        Util.centralizarFrame(ifrPoltronas);
        ifrPoltronas.setVisible(true);
    }//GEN-LAST:event_jPoltronaMenuActionPerformed

    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {                                        
        List<JRadioButton> radionButtons = getRadionButtons();
        if(!Util.listNuloOuVazio(radionButtons)) {

            List<JRadioButton> radiosButtonsSeleconados = radionButtons.stream().filter(radionButton -> radionButton.isSelected() && radionButton.isEnabled()).toList();
            List<Poltrona> poltronas = poltronaDao.findAll();
            List<Poltrona> poltronasSelecionadas = null;
            if(!Util.listNuloOuVazio(radiosButtonsSeleconados) && !Util.listNuloOuVazio(poltronas)) {
                poltronasSelecionadas = poltronas.stream().filter(poltrona ->
                        radiosButtonsSeleconados.stream().anyMatch(radionButton -> radionButton.getText().equals(poltrona.getCodigo()))).toList();

            }
            if(!Util.listNuloOuVazio(poltronasSelecionadas)){
                System.out.println("cria pedido...");
            }
        }

    }

    private void jMenuFilmeActionPerformed(java.awt.event.ActionEvent evt) {                                           
        IfrFilmes ifrFilmes = new IfrFilmes();
        jDesktopPane1.add(ifrFilmes);
        Util.centralizarFrame(ifrFilmes);
        ifrFilmes.setVisible(true);
    }

    private void jMenuSalaActionPerformed(java.awt.event.ActionEvent evt) {                                          
        IfrSalas ifrSalas = new IfrSalas();
        jDesktopPane1.add(ifrSalas);
        Util.centralizarFrame(ifrSalas);
        ifrSalas.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
                Conexao.getConexao();
            };
        });
    }

    private void verificaPoltronasCompradas() {
        List<Poltrona> poltronas = poltronaDao.buscaPoltronasIndisponiveis();
        List<JRadioButton> radionButtons = getRadionButtons();
        if(!Util.listNuloOuVazio(poltronas) && !Util.listNuloOuVazio(radionButtons)){
            poltronas.forEach(poltrona -> {
                radionButtons.forEach(jRadioButton -> {
                    if(poltrona.getCodigo().equals(jRadioButton.getText())){
                        jRadioButton.setEnabled(false);
                        jRadioButton.setSelected(true);
                    }
                });
            });
        }
    }

    private List<JRadioButton> getRadionButtons() {
        return new ArrayList<>(Arrays.asList(A1, A2, A3));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A1;
    private javax.swing.JRadioButton A2;
    private javax.swing.JRadioButton A3;
    private javax.swing.JButton comprar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jHorariosMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuFilme;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuSala;
    private javax.swing.JMenuItem jPoltronaMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
