/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cinema.view;

import com.mycompany.cinema.conexao.Conexao;
import com.mycompany.cinema.dao.PedidoDao;
import com.mycompany.cinema.dao.PoltronaDao;
import com.mycompany.cinema.entidade.HorarioSessao;
import com.mycompany.cinema.entidade.Poltrona;
import com.mycompany.cinema.util.Util;

import javax.swing.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author Arthur
 */
public class JFrame extends javax.swing.JFrame {
    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
        super.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuFilme = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuSala = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jHorariosMenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jHorario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastro");

        jMenuFilme.setText("Filmes");
        jMenuFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFilmeActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuFilme);
        jMenu1.add(jSeparator1);

        jMenuSala.setText("Salas");
        jMenuSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSala);
        jMenu1.add(jSeparator3);

        jHorariosMenu.setText("Horários");
        jHorariosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHorariosMenuActionPerformed(evt);
            }
        });
        jMenu1.add(jHorariosMenu);
        jMenu1.add(jSeparator2);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sessões");

        jHorario.setText("Horários");
        jHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHorarioActionPerformed(evt);
            }
        });
        jMenu2.add(jHorario);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jDesktopPane1)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jHorariosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHorariosMenuActionPerformed
        IfrHorarioSessao irfHorarioSessao = new IfrHorarioSessao();
        jDesktopPane1.add(irfHorarioSessao);
        Util.centralizarFrame(irfHorarioSessao);
        irfHorarioSessao.setVisible(true);
    }//GEN-LAST:event_jHorariosMenuActionPerformed

    private void jHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHorarioActionPerformed
        IfrHorarioSessaoListagem irfHorarioSessaoListagem = new IfrHorarioSessaoListagem();
        jDesktopPane1.add(irfHorarioSessaoListagem);
        Util.centralizarFrame(irfHorarioSessaoListagem);
        irfHorarioSessaoListagem.setVisible(true);
    }//GEN-LAST:event_jHorarioActionPerformed

    private void jMenuFilmeActionPerformed(java.awt.event.ActionEvent evt) {                                           
        IfrFilmes ifrFilmes = new IfrFilmes();
        jDesktopPane1.add(ifrFilmes);
        Util.centralizarFrame(ifrFilmes);
        ifrFilmes.setVisible(true);
    }

    private void jMenuSalaActionPerformed(java.awt.event.ActionEvent evt) {                                          
        IfrSalas ifrSalas = new IfrSalas();
        jDesktopPane1.add(ifrSalas);
        Util.centralizarFrame(ifrSalas);
        ifrSalas.setVisible(true);
    }

    public static void horarioSessaoListagem(HorarioSessao horarioSessao){
        IfrPoltronasListagem ifrPoltronasListagem = new IfrPoltronasListagem(horarioSessao);
        jDesktopPane1.add(ifrPoltronasListagem);
        Util.centralizarFrame(ifrPoltronasListagem);
        ifrPoltronasListagem.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame jFrame = new JFrame();
                jFrame.setVisible(true);
                windowsListener(jFrame);
                Conexao.getConexao();
            };
        });
    }

    public static void windowsListener(JFrame jFrame){
        jFrame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?",
                        "Sair",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (opcao == JOptionPane.YES_OPTION) {
                    jFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                }else{
                    jFrame.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jHorario;
    private javax.swing.JMenuItem jHorariosMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuFilme;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuSala;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
