/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cinema;

import com.mycompany.cinema.conexao.Conexao;
import com.mycompany.cinema.dao.PedidoDao;
import com.mycompany.cinema.dao.PoltronaDao;
import com.mycompany.cinema.entidade.Poltrona;
import com.mycompany.cinema.processo.Teste;
import com.mycompany.cinema.util.Util;

import javax.swing.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

/**
 *
 * @author Arthur
 */
public class JFrame extends javax.swing.JFrame {
    private final PoltronaDao poltronaDao = new PoltronaDao();
    private final PedidoDao pedidoDao = new PedidoDao();


    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
        verificaPoltronasCompradas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        A1 = new javax.swing.JRadioButton();
        A2 = new javax.swing.JRadioButton();
        A3 = new javax.swing.JRadioButton();
        comprar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        A1.setText("A-1");
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });

        A2.setText("A-2");

        A3.setText("A-3");
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });

        comprar.setText("COMPRAR");
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(A1)
                .addGap(18, 18, 18)
                .addComponent(A2)
                .addGap(18, 18, 18)
                .addComponent(A3)
                .addContainerGap(427, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comprar)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A1)
                    .addComponent(A2)
                    .addComponent(A3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(comprar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A1ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3ActionPerformed

    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarActionPerformed
        List<JRadioButton> radionButtons = getRadionButtons();
        if(!Util.nuloOuVazio(radionButtons)) {

            List<JRadioButton> radiosButtonsSeleconados = radionButtons.stream().filter(radionButton -> radionButton.isSelected() && radionButton.isEnabled()).toList();
            List<Poltrona> poltronas = poltronaDao.findAll();
            List<Poltrona> poltronasSelecionadas = null;
            if(!Util.nuloOuVazio(radiosButtonsSeleconados) && !Util.nuloOuVazio(poltronas)) {
                poltronasSelecionadas = poltronas.stream().filter(poltrona ->
                        radiosButtonsSeleconados.stream().anyMatch(radionButton -> radionButton.getText().equals(poltrona.getCodigo()))).toList();

            }
            if(!Util.nuloOuVazio(poltronasSelecionadas)){
                System.out.println("cria pedido...");
            }
        }

    }//GEN-LAST:event_comprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
                Conexao.getConexao();
            };
        });
    }

    private void verificaPoltronasCompradas() {
        List<Poltrona> poltronas = poltronaDao.buscaPoltronasIndisponiveis();
        List<JRadioButton> radionButtons = getRadionButtons();
        if(!Util.nuloOuVazio(poltronas) && !Util.nuloOuVazio(radionButtons)){
            poltronas.forEach(poltrona -> {
                radionButtons.forEach(jRadioButton -> {
                    if(poltrona.getCodigo().equals(jRadioButton.getText())){
                        jRadioButton.setEnabled(false);
                        jRadioButton.setSelected(true);
                    }
                });
            });
        }
    }

    private List<JRadioButton> getRadionButtons() {
        return new ArrayList<>(Arrays.asList(A1, A2, A3));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A1;
    private javax.swing.JRadioButton A2;
    private javax.swing.JRadioButton A3;
    private javax.swing.JButton comprar;
    // End of variables declaration//GEN-END:variables
}
